### Importing numpy as np

In [1]:
import numpy as np

### Create an array of 10 zeros

In [31]:
arr0= np.zeros(10)
arr0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### Create an array of 10 ones

In [4]:
arr1 = np.ones(10)
arr1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### Create an array of 10 fives

In [5]:
arr5 = arr1 * 5
arr5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

### Create an array of integers from 10-50

In [8]:
arr40 = np.arange(10,51)
arr40

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

### Create an array of even integers from 10-50

In [9]:
arrEven = np.arange(10,51,2)
arrEven

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

### Create a 3x3 matrix with valyes ranging from 0-8

In [10]:
matrix3 = np.array([[0,1,2],[3,4,5],[6,7,8]])
matrix3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Use NumPy to generate a random number between 0-1

In [16]:
random1 = np.random.rand(1)
random1

array([0.08484163])

### Creating a matrix using different statements and displaying them

In [34]:
#creating a matrix and rearanging its shape
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [35]:
#getting the sum of all the valyes in the mat matrix
sum_mat = mat.sum()
sum_mat

325

In [36]:
#Getting the standard deviation in the mat matrix
std_mat = mat.std()
std_mat

7.211102550927978

In [37]:
#Creating a new matrix of 25 ones
mat1 = np.ones(25)
mat1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1.])

In [38]:
#Reshaping the matrix of 25 ones
mat1 = np.ones(25).reshape(5,5)
mat1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [39]:
#Summing the two matrices
sum_mats = mat1 + mat
sum_mats

array([[ 2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16.],
       [17., 18., 19., 20., 21.],
       [22., 23., 24., 25., 26.]])

In [40]:
#Multiplying the values of the two matrices
mult_mats = mat1 * mat
mult_mats

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.]])